pub const GET_LOGIN_OPTIONS: &str = r#"query GetLoginOptions($input:UserOptionsInput!){getLoginOptions(input:$input){loginOptions{...LoginOptionsFragment}canUseEmailOTP phoneCollectionRequired authCode errors{...LoginOptionsErrorFragment}}}fragment LoginOptionsFragment on LoginOptions{loginId loginIdType emailId phoneNumber{number countryCode isoCountryCode}canUsePassword canUsePhoneOTP canUseEmailOTP loginPhoneLastFour maskedPhoneNumberDetails{loginPhoneLastFour countryCode isoCountryCode}loginMaskedEmailId signInPreference loginPreference lastLoginPreference hasRemainingFactors isPhoneConnected otherAccountsWithPhone loginMaskedEmailId hasPasskeyOnProfile accountDomain residencyRegion{residencyCountryCode residencyRegionCode}isIdentityMergeRequired requiresTokenBasedPasswordSetup}fragment LoginOptionsErrorFragment on IdentityLoginOptionsError{code message version}"#;

pub const SIGN_UP: &str = r#"mutation SignUp($input:SignUpInput!){signUp(input:$input){auth{...AuthFragment}authCode{authCode cid}errors{...ErrorFragment}generateOtpResult{...OtpResultFragment}isMandatory2FASetupRequired twoFALoginOptions{...TwoFALoginOptionsFragment}}}fragment AuthFragment on AuthResult{loginId loginIdType emailId phoneNumber{number countryCode}authCode identityToken}fragment ErrorFragment on IdentitySignUpError{code message}fragment OtpResultFragment on GenerateOTPResult{receiptId otpOperation otpType otherAccountsWithPhone action{alternateOption currentOption nextFactor}}fragment TwoFALoginOptionsFragment on TwoFALoginOptions{twoFALoginMethods{method isConfigured precedence identity{phoneNumber{number countryCode isoCountryCode}formattedMaskedPhoneNumber emailId maskedEmailId}}}"#;

pub const GENERATE_OTP: &str = r#"mutation GenerateOtp($input:GenerateOTPInput!){generateOTP(input:$input){errors{...GenerateOtpErrorFragment}otpResult{...GenerateOtpResultFragment}}}fragment GenerateOtpErrorFragment on IdentityGenerateOTPError{code message}fragment GenerateOtpResultFragment on GenerateOTPResult{receiptId otpOperation otpType otherAccountsWithPhone action{alternateOption currentOption}}"#;

pub const SHIPPING_COUNTRY_LIST: &str = r#"query shippingCountryList{shippingCountryList{countryDetails{code phoneCode flagAssetUrl name}errors{code}}}"#;

pub const SHIPPING_COUNTRY_LIST_V2: &str = r#"query shippingCountryListV2($input:ShippingCountryAndRegionListInput!){shippingCountryListV2(input:$input){countryDetails{code phoneCode flagAssetUrl name regions{code lang name}}errors{code}}}"#;

pub const GET_SIGNUP_MODULE: &str = r#"query getSignUpModule($pageType:String! $tenant:String! $tempo:JSON $isCustomModuleEnabled:Boolean = false){contentLayout(channel:"WWW" pageType:$pageType tenant:$tenant){modules(tempo:$tempo){name type version status schedule{start end priority expEnabled}triggers{pageType pageId zone inheritable}targeting configs{__typename...on TempoWM_GLASSWWWSignUpConfigs{logo{alt assetId assetName clickThrough{type value rawValue tag}height src title width size contentType}headingText{headingTitle}inputFields{inputFieldPlaceholder inputFieldLabel emptyInputFieldError invalidInputError}passwordReqs passwordReqsList{requirement requirementMet}checkboxes{checboxLabel checkboxValue checkboxDescription checkboxInfo{info}}termsAndPrivacyText links{link{linkText title clickThrough{type value rawValue}}}createAcctButton{createAcctButtonLabel}signInButton{signInText signInButtonLabel}hideMarketingEmailCheckboxByRegions legalNoticeText{title fontColor textFontWeight textFontSize legalNoticeRegion}}...SignInHeaderFragment @include(if:$isCustomModuleEnabled)...SignUpProgressBarFragment @include(if:$isCustomModuleEnabled)}publishedDate moduleId module_id matchedTrigger{pageType pageId zone inheritable}}layouts{id layout}}}fragment SignInHeaderFragment on TempoWM_GLASSWWWWalmartBusinessHeaderConfigs{backgroundColor walmartBusinessLogo:logo{src assetName contentType height size width assetId title alt uid}title{text}}fragment SignUpProgressBarFragment on TempoWM_GLASSWWWB2BSignUpProgressBarConfigs{header{text bold url}titleList{title{text bold url isChecked}}}"#;

pub const GET_SIGN_IN_TEMPO_MODULE: &str = r#"query getSignInTempoModule($pageType:String! $tenant:String! $tempo:JSON){contentLayout(channel:"WWW" pageType:$pageType tenant:$tenant){modules(tempo:$tempo){name type version status schedule{start end priority expEnabled}triggers{pageType pageId zone inheritable}targeting configs{__typename}publishedDate moduleId module_id matchedTrigger{pageType pageId zone inheritable}}layouts{id layout}}}"#;

pub const GET_VERIFY_YOUR_ACCOUNT_MODULE: &str = r#"query getVerifyYourAccountModule($pageType:String! $tempo:JSON $tenant:String!){contentLayout(channel:"WWW" pageType:$pageType tenant:$tenant){modules(tempo:$tempo){name type version status schedule{start end priority expEnabled}triggers{pageType pageId zone inheritable}targeting configs{__typename...on TempoWM_GLASSWWWVerifyYourAccountPageConfigs{logo{alt assetId assetName clickThrough{type value rawValue tag}height src title width size contentType}headerText enterSixDigitCodeText submitBtnText{submitBtnLabel ariaLabel}verificationType}}publishedDate moduleId module_id matchedTrigger{pageType pageId zone inheritable}}layouts{id layout}}}"#;

pub const CLIENT_ID: &str = "5f3fb121-076a-45f6-9587-249f0bc160ff";
pub const TENANT_ID: &str = "elh9ie";
pub const CALLBACK_URL: &str = "https://www.walmart.com/account/verifyToken";
pub const SCOPE: &str = "openid email offline_access";

pub const PLATFORM_VERSION: &str =
    "usweb-1.257.1-0460fd59551a48164583fe56e9aef35e85a51f4d-4240206r";

pub const DISCLAIMER_TEXT: &str = "By clicking Continue, you acknowledge you have read and agreed to our Terms of Use https://help.walmart.com/app/answers/detail/a_id/8 and Privacy Policy http://corporate.walmart.com/privacy-security/walmart-privacy-policy. Message and data rates may apply. View our Mobile Alerts Terms https://www.walmart.com/help/article/mobile-alerts-terms-of-use/499122d9bba94d08b50e8facf42fcc82.";

pub const DISCLAIMER_MODULE_ID: &str = "f3bb96c8-6c68-4a42-b00f-388409b42472";
pub const DISCLAIMER_MODULE_VERSION: &str = "19";
